### ISSUE TITLE
import dovpanda in console error - NameError: name 'display' is not defined 

### ISSUE THREAD

**Issue by uriyapes** [dovpanda-dev/dovpanda#71]
# Brief Description

I am getting the following error when importing dovpanda from inside the console :
NameError: name 'display' is not defined 

# System Information
WIN10-64bit

- Python version (required): 3.6.7

- Anaconda env:
![image](https://user-images.githubusercontent.com/28870991/68534610-0f230e00-033f-11ea-9ddc-7eb02e769636.png)

# Minimally Reproducible Code
>>> import pandas as pd                                                                                                 
>>> import numpy as np                                                                                                  
>>> import dovpanda 

# Error Messages

Traceback (most recent call last):                                                                                        File "<stdin>", line 1, in <module>                                                                                     File "C:\DevPrograms\Anaconda2\envs\test\lib\site-packages\dovpanda\__init__.py", line 7, in <module>                     from dovpanda.core import ledger                                                                                      File "C:\DevPrograms\Anaconda2\envs\test\lib\site-packages\dovpanda\core.py", line 7, in <module>                         ledger = Ledger()                                                                                                     File "C:\DevPrograms\Anaconda2\envs\test\lib\site-packages\dovpanda\base.py", line 119, in __init__                       self.teller = _Teller()                                                                                               File "C:\DevPrograms\Anaconda2\envs\test\lib\site-packages\dovpanda\base.py", line 34, in __init__                        self.set_output('display')                                                                                            File "C:\DevPrograms\Anaconda2\envs\test\lib\site-packages\dovpanda\base.py", line 103, in set_output                     self.output = display                                                                                               NameError: name 'display' is not defined

**Comment by DeanLa** [comment]
Good catch.
Will work on fix.
As a workaround - this will be solved if you `conda install jupyter`

**Comment by DeanLa** [comment]
fix applied to master. It will be up in the next pip release.

**Comment by DeanLa** [comment]
pip version released.
`pip install --upgrade dovpanda`

**Comment by nemesmihaly** [comment]
The error when importing dovpanda is still there (Python 3.6 and 3.8)
